import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,finance,notification,profile
}: Readonly<{
  children: React.ReactNode;
 finance:React.ReactNode;
 notification:React.ReactNode;
 profile:React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className=" w-full bg-blue-700 px-2 rounded-lg py-4  flex flex-wrap justify-between items-center ">
<Link className="font-bold text-2xl" href="/">Home</Link>
<Link className="font-bold text-2xl" href="/dashbord">dashbord</Link>
        </nav>
        {children}
       <div className="flex justify-between gap-2.5">
        <div className="border p-4 shadow-2xl border-blue-700 shadow-blue-700 rounded-xl">{finance}</div>
        <div className="border p-4 shadow-2xl border-blue-700 shadow-blue-700 rounded-xl">{notification}</div>
        <div className="border p-4 shadow-2xl border-blue-700 shadow-blue-700 rounded-xl">{profile}</div>
       </div>
      </body>
    </html>
  );
}
